const EVENTS = {
  USER_REGISTERED: 'USER_REGISTERED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  BOOKING_FAILED: 'BOOKING_FAILED'
};

module.exports = { EVENTS };
